// Assertion helpers
export {
  expectHealth,
  expectDamaged,
  expectBlock,
  expectBarrier,
  expectPower,
  expectNoPower,
  expectDead,
  expectAlive,
  expectPhase,
  expectVictory,
  expectDefeat,
  expectTurn,
  expectEnergy,
  expectEnemyCount,
  expectHandSize,
  expectDrawPileSize,
  expectDiscardPileSize,
  expectExhaustPileSize,
  expectCardInHand,
  expectCardNotInHand,
  expectCardInDiscard,
  expectCardInExhaust,
  expectStats,
  expectDamageDealt,
  expectDamageTaken,
  expectCardsPlayed,
  expectEnemiesKilled,
  expectGamePhase,
  expectFloor,
  expectGold,
} from './assertions'

// Action helpers
export {
  act,
  actSequence,
  playCard,
  playCards,
  playAllCardsAt,
  drawCards,
  discardCard,
  discardHand,
  endTurn,
  startTurn,
  endPlayerTurn,
  completeTurn,
  runTurns,
  dealDamage,
  heal,
  addBlock,
  applyPower,
  gainEnergy,
  spendEnergy,
  startCombat,
  endCombat,
  enemyAction,
  useActivatedAbility,
  useUltimateAbility,
} from './actions'

// Inspection helpers
export {
  getPlayer,
  getEnemy,
  getEntity,
  getAllEnemies,
  getEnemyCount,
  getFirstEnemy,
  getPower,
  getPowerAmount,
  hasPower,
  getPowerIds,
  getHand,
  getDrawPile,
  getDiscardPile,
  getExhaustPile,
  getHandSize,
  findCardInHand,
  findCardByUid,
  isCardInHand,
  getCardsFromHand,
  isInCombat,
  isPlayerTurn,
  isVictory,
  isDefeat,
  isCombatOver,
  getCurrentTurn,
  getCardsPlayedThisTurn,
  getCurrentEnergy,
  getMaxEnergy,
  getCombatPhase,
  getFloor,
  getGold,
  getHeroHealth,
  getHeroMaxHealth,
  getDeckSize,
  getRelicCount,
  hasRelic,
} from './inspect'
